### ISSUE TITLE
cooperation

### ISSUE THREAD

**Issue by saisaitian** [Akmazad/rDrugSimDB#1]
dear author:
  Could I have opprtunity to cooperate with you to develop this package?

**Comment by Akmazad** [comment]
Hi @saisaitian, do you have any prior experience in developing a Bioconductor R package?

**Comment by saisaitian** [comment]
Yes, I have experience in developing the CRAN R package. Your DrugSimDB were very interesting and I hope I can join it and develop it

**Comment by Akmazad** [comment]
Great. Would you mind sharing the name/link of the packages that you have developed? 
Thanks 


Sent from Yahoo Mail for iPhone


On Wednesday, July 27, 2022, 4:40 pm, saisaitian ***@***.***> wrote:




Yes, I have experience in developing the CRAN R package. Your DrugSimDB were very interesting and I hope I can join it and develop it

**Comment by saisaitian** [comment]
Hi, this is the link, https://github.com/saisaitian/TCMR, however this package is not finished and public

**Comment by Akmazad** [comment]
looks great to me. 
Re rDrugSimDB, let's discuss what features can be included in the rDrugSimDB package. For reference, you can have a look on its shiny app: http://vafaeelab.com/drugSimDB.html

**Comment by saisaitian** [comment]
Yes, In fact, I have repated your research and I have read it carefully. Could I ask a question? If we publish this package, may I be the first author ?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "A K M ***@***.***&gt;; 
发送时间: 2022年7月27日(星期三) 下午4:26
收件人: ***@***.***&gt;; 
抄送: "Saisai ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Akmazad/rDrugSimDB] cooperation (Issue #1)





 
looks great to me.
 Re rDrugSimDB, let's discuss what features can be included in the rDrugSimDB package. For reference, you can have a look on its shiny app: http://vafaeelab.com/drugSimDB.html

**Comment by Akmazad** [comment]
Hi @saisaitian, at this moment, let's focus on the research plans ahead, i.e., which features would be there in the **rDrugSimDB** to make it worthwhile for the community so that it would yield HQ research articles. Regarding the authorship sequence, the first authorship would not only depend on publishing the package but also on writing the manuscript for it.

**Comment by saisaitian** [comment]
ok，there is no problems, we focus on the research plans ahead

**Comment by Akmazad** [comment]
Great. I've added you as a collaborator to this repo. 
Initial Action plan:
1. Go through input files that may be required to develop the package (Download tab: http://vafaeelab.com/drugSimDB.html)
2. Come up with an idea of a tentative list of useful features.
3. Build the whole code-base around a few of the basic functionalities.

You can reach me via "azad_du28 at yahoo dot com"

Feel free to let me know anything you might need along the way, and welcome onboard.
